export const ActionTypes = {
  FETCH_DATA: "FETCH_DATA",
  CHANGE_INPUT: "CHANGE_INPUT",
  ADD_INPUT: "ADD_INPUT",
  SELECT_INPUT: "SELECT_INPUT",
  UPDATE_INPUT: "UPDATE_INPUT",
  DELETE_INPUT: "DELETE_INPUT",
  ADD_LOGS: "ADD_LOGS",
  ADD_UPDATE_LOGS: "ADD_UPDATE_LOGS",
};
